name: Deploy to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.vscode/**
            **/.idea/**
            **/drafts/**
            **/draft/**
            **/*.md
            **/*.sh
            .deployignore
            .github/
            README.md